### ISSUE TITLE
use GitHub pages

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot.NET#11]
build and deploy to GitHub pages (instead of Scott's personal hosting)

**Comment by swharden** [comment]
see notes in #14

**Comment by MareMare** [comment]
May I try this issue concerning the above notes?

**Comment by swharden** [comment]
Hi @MareMare, 

You're welcome to modify the action as described in #14 and even if we don't run it yet (let's not change the `on:` workflow triggers) improvements now will make it easier when the time comes!

https://github.com/ScottPlot/ScottPlot.NET/blob/ef6c661c23cb04d80124b9054d01becfbcf1235f/.github/workflows/gh-pages.yml#L1-L26

**Comment by MareMare** [comment]
Hi, @swharden, Thanks for your reply.
PR #16 was created.
Please review it sometime when it's good.
