### ISSUE TITLE
The chart cannot be scaled on the touch screen

### ISSUE THREAD

**Issue by deokoo** [ScottPlot/ScottPlot.NET#28]

**Comment by swharden** [comment]
Hi @deokoo, thanks for reporting this!

I have a laptop with a touch screen, and the following works:
* pan (touch-drag)
* zoom rectangle (alt + touch-drag)
* zoom in / zoom out (pinch)
* zoom in / out on one axis (pinch + ctrl or shift)

What's not easy is:
* auto-axis (middle click)
* drag zoom
... but for touch-only applications adding a button to do those things to the application is probably the way to go

What functionality are you unable to achieve on your device? What is your device?
