### ISSUE TITLE
icon isn't transparent

### ISSUE THREAD

**Issue by swharden** [ScottPlot/ScottPlot.NET#3]
![image](https://user-images.githubusercontent.com/4165489/135667868-981e4c88-2988-46c8-8549-dd799539c7a6.png)

**Comment by NeelPatel31** [comment]
Hey, Do you want this icon without background ?
https://raw.githubusercontent.com/ScottPlot/ScottPlot.NET/main/content/assets/images/favicon.ico

**Comment by swharden** [comment]
source icons are here https://github.com/ScottPlot/ScottPlot/tree/master/dev/icon

**Comment by swharden** [comment]
@NeelPatel31 if you want to give this a try:

* source icons are here: https://github.com/ScottPlot/ScottPlot/tree/master/dev/icon and if you replace 
* replace this file: https://github.com/ScottPlot/ScottPlot.NET/blob/main/content/assets/images/favicon.ico

When I merge the pull request the website will be updated automatically 👍 🚀

**Comment by NeelPatel31** [comment]
> @NeelPatel31 if you want to give this a try:
> 
> * source icons are here: https://github.com/ScottPlot/ScottPlot/tree/master/dev/icon
> * replace this file: https://github.com/ScottPlot/ScottPlot.NET/blob/main/content/assets/images/favicon.ico
> 
> When I merge the pull request the website will be updated automatically 👍 🚀

@swharden Thank you for showing me the issue.
Please check the PR which I have created.
