### ISSUE TITLE
Quickstart: Add ScottPlot5 information

### ISSUE THREAD

**Issue by heartacker** [ScottPlot/ScottPlot.NET#31]
the old is not fix for  SP5

<img src="https://github.com/ScottPlot/ScottPlot.NET/assets/1876302/3ad12e96-f542-409c-912a-eb95db96a3bb" width="50%">

**Comment by swharden** [comment]
Hi @heartacker, thanks for suggesting this!

My original plan was not to create ScottPlot 5 quickstarts until is completed and released and has a complete cookbook. However I recognize that the cookbook does appear in the menu, so it makes sense to have something about ScottPlot 5 written on the quickstarts page. We can also use it as an opportunity to link to https://scottplot.net/versions/

I'll leave this issue open to track progress toward creating a ScottPlot 5 quickstart, and hopefully I can have this complete later today. Thanks again for the suggestion!

**Comment by heartacker** [comment]
can you add page first， and may be after that there will be PRs from community

**Comment by swharden** [comment]
After discussing this on Discord, I'm trying a few different options:

## Separate Sections by Version

![image](https://github.com/ScottPlot/ScottPlot.NET/assets/4165489/e2619777-3418-451c-9446-a70e6fa9b773)

## Collapsible Code Samples

![image](https://github.com/ScottPlot/ScottPlot.NET/assets/4165489/55695401-8d2f-457d-98e9-327d62e867c4)

**Comment by swharden** [comment]
> can you add page first， and may be after that there will be PRs from community

Good idea! The main quickstart pages now have code for both versions, and they should be easy to edit by the community in the future 👍 

Thanks again for the suggestion!

**Comment by swharden** [comment]
Check out the new example on https://scottplot.net/quickstart/console/ (you may have to refresh)

What do you think of the new design?

**Comment by heartacker** [comment]
![image](https://github.com/ScottPlot/ScottPlot.NET/assets/1876302/31cb3985-5e0d-4010-87f2-0a7bb76d88d7)
 I think we can show them at the same time
